spring.application.name=ttan

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/java_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:database/migrations
spring.flyway.baseline-on-migrate=true

jwt.secret = dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9yand0c2lnbmluZzEyMzQ1Njc4OTA=
jwt.expiration = 86400000
